-- Y3D Creations — troca o catálogo antigo pelos produtos, fotos e preços reais (para bancos JÁ criados).
-- Aplique uma vez no MySQL do projeto. Só usa UPDATE/DELETE com WHERE.
SET NAMES utf8mb4;

INSERT INTO produtos (id, nome, descricao, preco, estoque, categoria_id, emoji, imagens, personalizacoes, detalhes, avaliacao, total_avaliacoes) VALUES (1, 'Chaveiros Nomes BTS', 'Chaveiros com o nome de cada integrante em relevo vermelho sobre base branca, com corrente de bolinhas. Vendidos por unidade.', 8.00, 100, 10, '🔑', '["/img/produtos/chaveiros-nomes-bts.jpg"]', '["Nome ou frase gravada", "Cores personalizadas"]', '["Peça física impressa em 3D pela Y3D Creations"]', NULL, 0)
ON DUPLICATE KEY UPDATE nome=VALUES(nome), descricao=VALUES(descricao), preco=VALUES(preco), estoque=VALUES(estoque), categoria_id=VALUES(categoria_id), emoji=VALUES(emoji), imagens=VALUES(imagens), personalizacoes=VALUES(personalizacoes), detalhes=VALUES(detalhes), avaliacao=VALUES(avaliacao), total_avaliacoes=VALUES(total_avaliacoes);

INSERT INTO produtos (id, nome, descricao, preco, estoque, categoria_id, emoji, imagens, personalizacoes, detalhes, avaliacao, total_avaliacoes) VALUES (2, 'Chaveiros Porta-Photocard', 'Chaveiro com moldura para photocard, em várias cores com detalhe holográfico e mosquetão. Ideal para levar seu bias sempre junto.', 15.00, 100, 10, '🖼️', '["/img/produtos/chaveiros-porta-photocard.jpg"]', '["Cores personalizadas"]', '["Peça física impressa em 3D pela Y3D Creations"]', NULL, 0)
ON DUPLICATE KEY UPDATE nome=VALUES(nome), descricao=VALUES(descricao), preco=VALUES(preco), estoque=VALUES(estoque), categoria_id=VALUES(categoria_id), emoji=VALUES(emoji), imagens=VALUES(imagens), personalizacoes=VALUES(personalizacoes), detalhes=VALUES(detalhes), avaliacao=VALUES(avaliacao), total_avaliacoes=VALUES(total_avaliacoes);

INSERT INTO produtos (id, nome, descricao, preco, estoque, categoria_id, emoji, imagens, personalizacoes, detalhes, avaliacao, total_avaliacoes) VALUES (3, 'Bandejas BT21', 'Bandejinhas ovais com rostinhos dos personagens BT21, ótimas para guardar anéis, clipes e pequenos objetos na mesa.', 19.90, 100, 2, '🧸', '["/img/produtos/bandejas-bt21.jpg"]', '["Personagem à escolha", "Cores personalizadas"]', '["Peça física impressa em 3D pela Y3D Creations"]', NULL, 0)
ON DUPLICATE KEY UPDATE nome=VALUES(nome), descricao=VALUES(descricao), preco=VALUES(preco), estoque=VALUES(estoque), categoria_id=VALUES(categoria_id), emoji=VALUES(emoji), imagens=VALUES(imagens), personalizacoes=VALUES(personalizacoes), detalhes=VALUES(detalhes), avaliacao=VALUES(avaliacao), total_avaliacoes=VALUES(total_avaliacoes);

INSERT INTO produtos (id, nome, descricao, preco, estoque, categoria_id, emoji, imagens, personalizacoes, detalhes, avaliacao, total_avaliacoes) VALUES (4, 'Porta-Óculos Fofinho', 'Suporte em formato de bichinho para apoiar seus óculos sem riscar. Disponível em ovelhinha e coelhinho.', 29.90, 100, 2, '👓', '["/img/produtos/porta-oculos-ovelha.jpg", "/img/produtos/porta-oculos-coelho.jpg"]', '["Modelo (ovelha ou coelho)", "Cores personalizadas"]', '["Peça física impressa em 3D pela Y3D Creations"]', NULL, 0)
ON DUPLICATE KEY UPDATE nome=VALUES(nome), descricao=VALUES(descricao), preco=VALUES(preco), estoque=VALUES(estoque), categoria_id=VALUES(categoria_id), emoji=VALUES(emoji), imagens=VALUES(imagens), personalizacoes=VALUES(personalizacoes), detalhes=VALUES(detalhes), avaliacao=VALUES(avaliacao), total_avaliacoes=VALUES(total_avaliacoes);

INSERT INTO produtos (id, nome, descricao, preco, estoque, categoria_id, emoji, imagens, personalizacoes, detalhes, avaliacao, total_avaliacoes) VALUES (5, 'Estátua Guerreira com Espada', 'Estátua colorida de personagem com jaqueta amarela, trança roxa e espada, impressa em várias cores e com base decorada. Peça de destaque para estante.', 180.00, 100, 1, '🗡️', '["/img/produtos/estatua-guerreira.jpg"]', '[]', '["Peça física impressa em 3D pela Y3D Creations"]', NULL, 0)
ON DUPLICATE KEY UPDATE nome=VALUES(nome), descricao=VALUES(descricao), preco=VALUES(preco), estoque=VALUES(estoque), categoria_id=VALUES(categoria_id), emoji=VALUES(emoji), imagens=VALUES(imagens), personalizacoes=VALUES(personalizacoes), detalhes=VALUES(detalhes), avaliacao=VALUES(avaliacao), total_avaliacoes=VALUES(total_avaliacoes);

INSERT INTO produtos (id, nome, descricao, preco, estoque, categoria_id, emoji, imagens, personalizacoes, detalhes, avaliacao, total_avaliacoes) VALUES (6, 'Grinch na Poltrona', 'Miniatura do Grinch sentado em uma poltrona capitonê vermelha, com acabamento detalhado. Perfeita para decoração de Natal.', 40.00, 100, 1, '🎄', '["/img/produtos/grinch-poltrona.jpg"]', '[]', '["Peça física impressa em 3D pela Y3D Creations"]', NULL, 0)
ON DUPLICATE KEY UPDATE nome=VALUES(nome), descricao=VALUES(descricao), preco=VALUES(preco), estoque=VALUES(estoque), categoria_id=VALUES(categoria_id), emoji=VALUES(emoji), imagens=VALUES(imagens), personalizacoes=VALUES(personalizacoes), detalhes=VALUES(detalhes), avaliacao=VALUES(avaliacao), total_avaliacoes=VALUES(total_avaliacoes);

INSERT INTO produtos (id, nome, descricao, preco, estoque, categoria_id, emoji, imagens, personalizacoes, detalhes, avaliacao, total_avaliacoes) VALUES (7, 'Bailarina Rosa', 'Escultura de bailarina em estilo low poly com saia em camadas e degradê de cores. Ótima para decorar mesa ou estante.', 35.00, 100, 1, '🩰', '["/img/produtos/bailarina-rosa.jpg"]', '["Cores personalizadas"]', '["Peça física impressa em 3D pela Y3D Creations"]', NULL, 0)
ON DUPLICATE KEY UPDATE nome=VALUES(nome), descricao=VALUES(descricao), preco=VALUES(preco), estoque=VALUES(estoque), categoria_id=VALUES(categoria_id), emoji=VALUES(emoji), imagens=VALUES(imagens), personalizacoes=VALUES(personalizacoes), detalhes=VALUES(detalhes), avaliacao=VALUES(avaliacao), total_avaliacoes=VALUES(total_avaliacoes);

INSERT INTO produtos (id, nome, descricao, preco, estoque, categoria_id, emoji, imagens, personalizacoes, detalhes, avaliacao, total_avaliacoes) VALUES (8, 'Bailarina Azul', 'Escultura de bailarina em estilo low poly com saia em camadas e degradê de cores. Ótima para decorar mesa ou estante.', 35.00, 100, 1, '🩰', '["/img/produtos/bailarina-azul.jpg"]', '["Cores personalizadas"]', '["Peça física impressa em 3D pela Y3D Creations"]', NULL, 0)
ON DUPLICATE KEY UPDATE nome=VALUES(nome), descricao=VALUES(descricao), preco=VALUES(preco), estoque=VALUES(estoque), categoria_id=VALUES(categoria_id), emoji=VALUES(emoji), imagens=VALUES(imagens), personalizacoes=VALUES(personalizacoes), detalhes=VALUES(detalhes), avaliacao=VALUES(avaliacao), total_avaliacoes=VALUES(total_avaliacoes);

INSERT INTO produtos (id, nome, descricao, preco, estoque, categoria_id, emoji, imagens, personalizacoes, detalhes, avaliacao, total_avaliacoes) VALUES (9, 'Dinossauros Equilibristas', 'Jogo de equilíbrio com base curva e dinossauros coloridos para empilhar sem deixar cair. Diversão para crianças e adultos.', 49.90, 100, 3, '🦖', '["/img/produtos/dinossauros-equilibrio.jpg"]', '[]', '["Peça física impressa em 3D pela Y3D Creations"]', NULL, 0)
ON DUPLICATE KEY UPDATE nome=VALUES(nome), descricao=VALUES(descricao), preco=VALUES(preco), estoque=VALUES(estoque), categoria_id=VALUES(categoria_id), emoji=VALUES(emoji), imagens=VALUES(imagens), personalizacoes=VALUES(personalizacoes), detalhes=VALUES(detalhes), avaliacao=VALUES(avaliacao), total_avaliacoes=VALUES(total_avaliacoes);

-- Produtos antigos (ids 10 a 26): apaga os que nunca foram pedidos e zera o estoque dos que já têm pedido.
DELETE FROM produtos WHERE id BETWEEN 10 AND 26 AND id NOT IN (SELECT produto_id FROM pedido_itens);
UPDATE produtos SET estoque = 0 WHERE id BETWEEN 10 AND 26;
